config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'pages#home'

  resources :vehicles, except: [:new, :create]

  resources :users, only: [:show] do
    resources :vehicles, only: [:index, :new, :create]
    resources :bookings, only: [:index]
  end

  resources :vehicles, only: [:new, :create] do
    resources :bookings, only: [:new, :create, :edit, :update]
  end

  resources :bookings, only: [:show, :destroy] do
    resources :reviews, only: [ :create ]
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :renter, class_name: "User"
  belongs_to :vehicle
  has_many :reviews
  validates :start_date, presence: true
  validates :number_of_nights, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    if params[:user_id]
      @my_bookings = policy_scope(Booking).where(renter_id: params[:user_id])
      @their_bookings = policy_scope(Booking).joins(:vehicle).merge(Vehicle.where(owner_id: params[:user_id]))
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @review = Review.new
    @reviews = Review.where(booking: @booking)
    authorize @booking
  end

  def new
    @booking = Booking.new
    @vehicle = Vehicle.find(params[:vehicle_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @vehicle = Vehicle.find(params[:vehicle_id])
    @booking.vehicle = @vehicle
    @booking.renter = current_user
    authorize @booking
    @booking.save
    redirect_to booking_path(@booking)
  end

  def edit
    @booking = Booking.find(params[:id])
    @vehicle = Vehicle.find(params[:vehicle_id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      authorize @booking
      redirect_to booking_path(@booking)
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    authorize @booking
    redirect_to user_bookings_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :number_of_nights)
  end
end

app/views/bookings/_form.html.erb
<div class="container mb-3">
<%= simple_form_for [@vehicle, @booking] do |f| %>
  <%= f.input :start_date, label:'Start date' %>
  <%= f.input :number_of_nights, label:'Number of nights' %>
  <%= f.button :submit, "Create!", class: "form-button" %>
<% end %>

</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/edit.html.erb
 <div class=" mt-5 container">
  <h1>Edit a Vehicle</h1>
  <%= render "form"  %>
</div>

app/views/bookings/index.html.erb
<div class="container mt-5">

  <h1>My bookings</h1>

  <div class="cards-wrapper w-100 p-3">
    <% @my_bookings.each do |booking| %>
      <div class="vehicle-index-card mb-3 w-75">
        <%= cl_image_tag booking.vehicle.photo, height: 300, width: 400 %>
        <div class="vehicle-index-card-content d-flex flex-column p-3">
          <p class="vehicle-index-card-title mb-2"><%= booking.vehicle.name %></p>
          <p class="vehicle-index-card-subheading"><%= booking.vehicle.berths %> berth <%= booking.vehicle.category %></p>
          <p class="vehicle-index-card-subheading">Total price: £<%= booking.vehicle.price_per_night * booking.number_of_nights %></p>
          <p class="vehicle-index-card-text flex-grow-1"><%= booking.vehicle.description[0..140] %></p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>




  <!--  -->

  <h1>Bookings for my vehicles</h1>

<% @their_bookings.each do |booking| %>
  <div class="card m-3" style="width: 50%; height: 400px;">
    <%= cl_image_tag booking.vehicle.photo, crop: :fill, :height=>200 %>
    <div class="card-body">
      <p class="card-text booking-card-text">From the <%= booking.start_date.to_s(:short) %> for <%= booking.number_of_nights %> nights</p>
      <h5 class="card-title"> <%= booking.vehicle.name %> </h5>
      <p class="card-text booking-card-text"> <%= booking.vehicle.berths %> berth <%= booking.vehicle.category %> </p>
    </div>
    <div class="card-body border-top w-">
      <%= link_to "Booking Details", booking_path(booking) %>
    </div>
  </div>
<% end %>

app/views/bookings/new.html.erb
<div class="container">
  <h1 class="mt-5">Review and Confirm Your Booking</h1>
  <div class ="confirm-container w-100 my-5 mx-auto px-5">
      <div class="vehicle-details-container d-flex pt-5 pb-3">

        <%= cl_image_tag @vehicle.photo %>
        <div class="ml-3">
          <h2><%= @vehicle.name %></h2>
          <p><%= @vehicle.category %></p>
          <p>Number of berths: <%= @vehicle.berths %></p>
          <p><%= @vehicle.description %></p>
        </div>
      </div>

      <div class="booking-details-container py-4">
        <table class="booking-table">
          <tr>
            <th><p><strong>Dates</strong></p></th>
            <td><p><%= Date.parse(params[:start_date]).strftime("%d %b") %> to <%= Date.parse(params[:end_date]).strftime("%d %b %Y") %> (<%= distance_of_time_in_words(params[:end_date],  params[:start_date]) %>)</p></td>
          </tr>
          <tr>
            <th><p><strong>Pickup Details</strong></p></th>
            <td><p>Please pick-up <%= @vehicle.name %> from <%= @vehicle.address.capitalize %> on <%= Date.parse(params[:start_date]).strftime("%d %b %Y") %> between 14.00 and 16.00.</p></td>
          </tr>
          <tr>
            <th><p><strong>Total Price</strong></p></th>
            <td><p class="vehicle-index-card-text-price"> £<%= (params[:end_date].to_i - params[:start_date].to_i) * @vehicle.price_per_night %> (<%= params[:end_date].to_i - params[:start_date].to_i %> x £<%= @vehicle.price_per_night %>)</p></td>
          </tr>
        </table>

        <div class="d-flex justify-content-between w-100">
          <%= link_to "Back", vehicle_path(@vehicle), class: "btn btn_secondary mt-3 ml-4"%>
          <%= simple_form_for([@vehicle, Booking.new]) do |f| %>
            <%= f.input :start_date, as: :hidden, input_html: { value: params[:start_date] } %>
            <%= f.input :number_of_nights, as: :hidden, input_html: { value: params[:end_date].to_i - params[:start_date].to_i } %>
            <%= f.submit "Confirm", class: "btn btn-primary" %>
          <% end %>
        </div>

      </div>

  </div>








</div>

app/views/bookings/show.html.erb
<div class="container mt-5">
  <h1>Your Booking</h1>

    <div class="vehicle-index-card mt-5 mb-3 w-100">
      <%= cl_image_tag @booking.vehicle.photo, height: 300 %>
      <div class="vehicle-index-card-content d-flex flex-column p-3">
        <p class="vehicle-index-card-title mb-2"><%= @booking.vehicle.name %></p>
        <p class="vehicle-index-card-subheading"><%= @booking.vehicle.berths %> berth <%= @booking.vehicle.category %></p>
        <p class="vehicle-index-card-text flex-grow-1"><%= @booking.vehicle.description[0..140] %></p>
        <p class="vehicle-index-card-text">On <%= @booking.start_date.to_s(:short) %> for <%= @booking.number_of_nights %> nights.</p>
        <p class="vehicle-index-card-text">Total price: £<%= @booking.vehicle.price_per_night * @booking.number_of_nights %></p>
      </div>
    </div>

  <%#= link_to "Add a review", new_vehicle_review_path(@booking.vehicle), class: "btn btn-primary" %>
   <!-- <h1>All reviews</h1> -->
  <%# @reviews.each do |review| %>
   <!-- <p><%#= review.comment %></p> -->
  <%# end %>
  <%#= simple_form_for([@booking, @review]) do |f| %>
    <%#= f.input :rating %>
    <%#= f.input :comment %>
    <%#= f.submit "Add a review" %>
  <%# end %>

  <% if policy(@booking).edit? %>
    <%= link_to "Edit Booking", edit_vehicle_booking_path(@booking.vehicle) , class: "btn btn-primary" %>
    <%= link_to "Delete Booking", booking_path, method: :delete, class: "btn btn_secondary m-0" %>
  <% end %>

</div>