config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'pages#home'

  resources :vehicles, except: [:new, :create]

  resources :users, only: [:show] do
    resources :vehicles, only: [:index, :new, :create]
    resources :bookings, only: [:index]
  end

  resources :vehicles, only: [:new, :create] do
    resources :bookings, only: [:new, :create, :edit, :update]
  end

  resources :bookings, only: [:show, :destroy] do
    resources :reviews, only: [ :create ]
  end

end

app/views/shared/_navbar.html.erb
<div class="navbar justify-content-between align-items-center navbar-expand-sm navbar-dark bg-primary px-3 py-0">
  <%= link_to "Cara", root_path, id: "nblogo", class: "navbar-brand mx-2" %>
  <%= yield %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
      <div class="collapse navbar-collapse flex-shrink-1 flex-grow-0" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Rent out your camper", new_user_vehicle_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "My bookings", user_bookings_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Help", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <%= cl_image_tag current_user.photo, class: "avatar nav-avatar ml-4 mr-3 dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Add Vehicle", new_user_vehicle_path(current_user), class: "dropdown-item" %>
                <%= link_to "My Vehicles", user_vehicles_path(current_user), class: "dropdown-item" %>
                <%= link_to "Manage Account", edit_user_registration_path(current_user), class: "dropdown-item" %>
                <%= link_to "Manage Bookings", user_bookings_path(current_user), class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Rent out your camper", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Help", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
        </nav>
    </div>

app/views/shared/_search_bar.html.erb
<form class="form-inline flex-grow-1 mx-5" action="/vehicles">
  <div class="row w-100">
    <div class="col-10">
      <%= render 'hidden_search_fields' %>
      <input class="form-control w-100" type="text" name="location" placeholder="Enter a location..." id="vehicle_address" value="<%= @search_params ? @search_params[:location] : "" %>">
    </div>
    <div class="col-2">
      <input class="form-control btn btn-light" type="submit" value="Search">
    </div>
  </div>
</form>