config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'pages#home'

  resources :vehicles, except: [:new, :create]

  resources :users, only: [:show] do
    resources :vehicles, only: [:index, :new, :create]
    resources :bookings, only: [:index]
  end

  resources :vehicles, only: [:new, :create] do
    resources :bookings, only: [:new, :create, :edit, :update]
  end

  resources :bookings, only: [:show, :destroy] do
    resources :reviews, only: [ :create ]
  end

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :owner, class_name: "User"
  has_many :bookings
  has_many :reviews, through: :bookings
  has_many :renters, through: :bookings, source: :renter
  validates :name, presence: true
  validates :berths, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :address, presence: true
  validates :price_per_night, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["Campervan", "Caravan", "Trailer Tent", "Motorhome"] }
  validates :description, presence: true, length: { in: 140..500 }
  validates :photo, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def average_rating
    return 0 if reviews.count == 0
    reviews.map(&:rating).sum / reviews.count
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @search_params = search_params
    @vehicles = policy_scope(Vehicle).all

    if @search_params[:location] && @search_params[:distance]
      # Filter by distance when location and distance presence
      @vehicles = @vehicles.near(@search_params[:location], search_params[:distance])
      @vehicles.each { |vehicle| vehicle[:distance] = vehicle.distance_to(@search_params[:location]).round }
      @vehicles = @vehicles.sort_by { |vehicle| vehicle[:distance] }
    end

    if @search_params[:price_per_night]
      @vehicles = @vehicles.select { |vehicle| vehicle.price_per_night < @search_params[:price_per_night] }
    end

    if @search_params[:berths]
      @vehicles = @vehicles.select { |vehicle| vehicle.berths == @search_params[:berths] }
    end

    if @search_params[:category]
      @vehicles = @vehicles.select { |vehicle| vehicle.category == @search_params[:category] }
    end
    @markers = generate_markers(@vehicles)
  end

  def show
    authorize @vehicle
    @markers = [{ lat: @vehicle.latitude, lng: @vehicle.longitude }]
    @search_params = search_params
  end

  def new
    @vehicle = Vehicle.new
    @user = User.find(params[:user_id])
    authorize @vehicle
  end

  def edit
    authorize @vehicle
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.owner = current_user
    authorize @vehicle
    if @vehicle.save
      redirect_to vehicle_path(@vehicle)
    else
      render :new
    end
  end

  def update
    if @vehicle.update(vehicle_params)
      authorize @vehicle
      redirect_to vehicle_path(@vehicle)
    else
      render :edit
    end
  end

  def destroy
    @vehicle.destroy
    redirect_to vehicles_path
    authorize @vehicle
  end

  # def average(column_name)
  #   calculate(:average, :reviews)
  # end


  private

  def vehicle_params
    params.require(:vehicle).permit(:name, :berths, :address, :price_per_night, :category, :description, :photo)
  end

  def search_params
    search_params = {}

    if params[:location] == "" || params[:location].nil? then search_params[:location] = nil
    else search_params[:location] = params[:location]
    end

    if params[:start_date] == "" || params[:start_date].nil? then search_params[:start_date] = nil
    else search_params[:start_date] = params[:start_date]
    end

    if params[:end_date] == "" || params[:end_date].nil? then search_params[:end_date] = nil
    else search_params[:end_date] = params[:end_date]
    end

    if params[:berths] == "" || params[:berths].nil? then search_params[:berths] = nil
    else search_params[:berths] = params[:berths].to_i
    end

    if params[:category] == "" || params[:category].nil? then search_params[:category] = nil
    else search_params[:category] = params[:category]
    end

    if params[:distance] == "" || params[:distance].nil? then search_params[:distance] = nil
    else search_params[:distance] = params[:distance].to_i
    end

    if params[:price_per_night] == "" || params[:price_per_night].nil? then search_params[:price_per_night] = nil
    else search_params[:price_per_night] = params[:price_per_night].to_i
    end

    return search_params
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def generate_markers(vehicles)
    vehicles.map do |vehicle|
      {
        lat: vehicle.latitude,
        lng: vehicle.longitude,
        name: vehicle.name,
        price_per_night: vehicle.price_per_night
      }
    end
  end
end

app/views/vehicles/_form.html.erb
<div class="container mb-3">
  <%= simple_form_for [@user, @vehicle] do |f| %>
    <%= f.input :name %>
    <%= f.input :berths %>
    <%= f.input :address %>
    <%= f.input :price_per_night %>
    <%= f.input :category, collection: ["Campervan", "Caravan", "Trailer Tent", "Motorhome"] %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Add Vehicle", class: "btn btn-primary" %>
 <% end %>

</div>

app/views/vehicles/_hidden_search_fields.html.erb
<% @search_params.each do |key, value| %>
  <% if value %>
    <input type="hidden" name="<%= key %>" value="<%= value %>">
  <% end %>
<% end %>

app/views/vehicles/_search_filters.html.erb
<div class="search-filter-buttons px-3 border-bottom">

  <% if @search_params[:start_date] && @search_params[:end_date] %>
    <button type="button" class="btn btn-primary mr-2" data-container="body" data-toggle="popover" data-placement="bottom"><%= @search_params[:start_date] %> - <%= @search_params[:end_date] %></button>
  <% else %>
    <button type="button" class="btn btn-outline-primary mr-2" data-container="body" data-toggle="popover" data-placement="bottom">Dates</button>
  <% end %>

  <% if @search_params[:berths]%>
    <button type="button" class="btn btn-primary mr-2" data-container="body" data-toggle="popover" data-placement="bottom"><%= @search_params[:berths] %> Berths</button>
  <% else %>
    <button type="button" class="btn btn-outline-primary mr-2" data-container="body" data-toggle="popover" data-placement="bottom">Berths</button>
  <% end %>

  <% if @search_params[:category] %>
    <button type="button" class="btn btn-primary mr-2" data-container="body" data-toggle="popover" data-placement="bottom"><%= @search_params[:category] %>s</button>
  <% else %>
    <button type="button" class="btn btn-outline-primary mr-2" data-container="body" data-toggle="popover" data-placement="bottom">Category</button>
  <% end %>

  <% if @search_params[:price_per_night] %>
    <button type="button" class="btn btn-primary mr-2" data-container="body" data-toggle="popover" data-placement="bottom">Up to £<%= @search_params[:price_per_night] %></button>
  <% else %>
    <button type="button" class="btn btn-outline-primary mr-2" data-container="body" data-toggle="popover" data-placement="bottom">Price Per Night</button>
  <% end %>

  <% if @search_params[:distance] && @search_params[:location] %>
    <button type="button" class="btn btn-primary mr-2" data-container="body" data-toggle="popover" data-placement="bottom">Up to <%= @search_params[:distance] %> miles</button>
  <% elsif @search_params[:location] %>
    <button type="button" class="btn btn-outline-primary mr-2" data-container="body" data-toggle="popover" data-placement="bottom">Distance</button>
  <% else %>
    <button class="d-none"></button>
  <% end %>

</div>

<div class="search-filter-popovers d-none">
  <div>
    <form class="" action="/vehicles">
      <%= render 'hidden_search_fields' %>
      <div class="popover-datepicker d-flex p-3 align-items-center">
        <input type="hidden" type="text" name="start_date" id="start_date" value="<%= @search_params[:start_date] %>">
        <input type="hidden" type="text" name="end_date" id="end_date" value="<%= @search_params[:end_date] %>">
      </div>
      <div class="popover-button-wrapper p-3">
        <input class="form-control btn btn-primary" type="submit" value="Apply">
      </div>
    </form>
  </div>
  <div class="p-3">
    <form class="" action="/vehicles">
      <%= render 'hidden_search_fields' %>
      <div class="form-group">
        <label for="berths">Enter number of berths:</label>
        <div class="input-group">
          <input class="form-control" type="number" name="berths" id="berths" value="<%= @search_params[:berths] %>"  placeholder="e.g. 4">
          <div class="input-group-append">
              <span class="input-group-text"> berths </span>
          </div>
        </div>
      </div>
      <input class="form-control btn btn-primary mt-3" type="submit" value="Apply">
    </form>
  </div>
  <div class="p-3">
    <form class="" action="/vehicles">
      <%= render 'hidden_search_fields' %>
      <% ["Campervan", "Caravan", "Trailer Tent", "Motorhome"].each do |vehicle| %>
        <div class="form-check">
          <input class="form-check-input" type="radio" value="<%= vehicle %>" id="<%= vehicle %>" name="category" <%= @search_params[:category] == vehicle ? "checked" : "" %>>
          <label class="form-check-label" for="<%= vehicle %>">
            <%= vehicle %>
          </label>
        </div>
      <% end %>
      <input class="form-control btn btn-primary mt-3" type="submit" value="Apply">
    </form>
  </div>
  <div class="p-3">
    <form class="" action="/vehicles">
      <%= render 'hidden_search_fields' %>
      <div class="form-group">
        <label for="price_per_night">Enter your max price:</label>
        <input type="hidden" name="price_per_night" id="price_per_night" value="<%= @search_params[:price_per_night] %>">
        <div class="price-slider my-3"></div>
        <p class="price-slider-text text-center"></p>
      </div>
      <input class="form-control btn btn-primary mt-3" type="submit" value="Apply">
    </form>
  </div>
  <div class="p-3">
    <form class="" action="/vehicles">
      <%= render 'hidden_search_fields' %>
      <div class="form-group">
        <label for="distance">Enter max distance:</label>
        <div class="input-group">
          <input class="form-control" type="number" name="distance" id="distance" value="<%= @search_params[:distance] %>" placeholder="e.g. 10">
          <div class="input-group-append">
              <span class="input-group-text"> miles </span>
          </div>
        </div>
      </div>
      <input class="form-control btn btn-primary mt-3" type="submit" value="Apply">
    </form>
  </div>
</div>

app/views/vehicles/edit.html.erb
<h1>Vehicles#edit</h1>
<p>Find me in app/views/vehicles/edit.html.erb</p>

app/views/vehicles/index.html.erb
<%= render('search_filters') %>
<div class="vehicles-index-wrapper">
  <div class="cards-wrapper w-50 p-3">
    <% if @vehicles.empty? %>
    <h2>Sorry, no results found!</h2>
    <% end %>
    <% @vehicles.each do |vehicle| %>
      <%= link_to vehicle_path(vehicle), class: 'text-decoration-none' do %>
        <div class="vehicle-index-card mb-3 w-100">
          <%= cl_image_tag vehicle.photo, height: 300 %>
          <div class="position-relative d-flex flex-column p-3">
            <p class="vehicle-index-card-title mb-2"><%= vehicle.name %></p>
            <p class="vehicle-index-card-subheading"><%= vehicle.berths %> berth <%= vehicle.category %></p>
            <p class="vehicle-index-card-text flex-grow-1"><%= vehicle.description[0..80] %>...</p>
            <div class="d-flex">
              <p class="vehicle-index-card-address mb-0 flex-grow-1">
                <% if vehicle[:distance] %>
                  <i class="fas fa-map-marker-alt mr-1"></i><%= pluralize vehicle[:distance].round, "mile" %> away
                <% end %>
              </p>
              <div class="vehicle-index-card-price">
                <h2>£<%= vehicle.price_per_night %></h2>
                <p>per night</p>
              </div>
              <div class="vehicle-index-card-rating">
                <% if vehicle.average_rating > 0 %>
                  <span><%= ('<i class="fas fa-star"></i>' * vehicle.average_rating).html_safe %></span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="map-wrapper">
    <div
      id="map"
      style="width: 100%;
      height: 100%;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/vehicles/new.html.erb
<div class=" mt-5 container">
  <h1>Add a Vehicle</h1>
  <%= render "form"  %>
</div>

app/views/vehicles/show.html.erb
<div class="container border-radius mb-5">
  <div class="top-image" style="background-image: url(<%= cl_image_path @vehicle.photo, crop: :mpad %>)">
  </div>
  <div class="content-container d-flex justify-content-between">
    <div class="details-container w-50">
      <div class="title-container d-flex justify-content-between align-items-center">
          <div class="vehicle-fields">
            <h1><%= @vehicle.name %></h1>
            <p><i class="mr-1 fas fa-map-marker-alt"></i> <%= @vehicle.address.capitalize %></p>
            <div class="d-flex">
              <p><i class="mr-1 fas fa-shuttle-van"></i> <%= @vehicle.category %> </p>
              <p> <i class="ml-3 fas fa-bed"></i> <%= @vehicle.berths %> Berths</p>
            </div>
          </div>
          <div>
            <%= link_to user_path(@vehicle.owner), class: 'text-decoration-none' do %>
            <div>
              <%= cl_image_tag @vehicle.owner.photo, crop: :fill, height: 80, width: 80 %>
              <p class="text-center"><%= @vehicle.owner.first_name %></p>
            </div>
            <% end %>
          </div>
      </div>


      <div class="description">
        <p><%= @vehicle.description %></p>
      </div>
      <h2 class="mb-5">Location</h2>
      <div
        id="map"
        style="width: 100%;
        height: 500px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <div class="booking-container">
      <div class="box-with-shadow border-radius sticky-top">
          <div class="price d-flex">
            <h4><strong>£<%= @vehicle.price_per_night %></strong></h4>
            <p> per night</p>
          </div>
          <div>
            <form class="popover-datepicker" action="<%=new_vehicle_booking_path(@vehicle)%>" >
              <div class="row">
                <div class="col-6"><input class="w-100 form-control" type="text" name="start_date" id="start_date_show" autocomplete="off" placeholder="Start date"></div>
                <div class="col-6"><input class="w-100 form-control" type="text" name="end_date" id="end_date_show" autocomplete="off" placeholder="End date"></div>
              </div>
              <input class="form-control btn btn-primary mt-3" type="submit" value="Book Now">
            </form>
          </div>

        </div>
      </div>
  </div>

    <h2 class="mb-4"><%= pluralize @vehicle.reviews.count, "Review" %>
      <span class="review-stars"><% @vehicle.average_rating.times do  %>
        <i class="fas fa-star star-color"></i>
      <% end %>
      </span>
    </h2>
    <% @vehicle.reviews.each do |review| %>
  <div class="card-product review-card my-3 p-4">
    <%= cl_image_tag review.user.photo, class: "avatar m-3" %>
    <strong><%= review.user.first_name %></strong>
    <%= ('<i class="fas fa-star star-color"></i>' * review.rating).html_safe %>
    <div class="card-product-infos">
      <%= review.comment %>
    </div>
  </div>
    <% end %>
</div>